### ISSUE TITLE
Needs higher version  of Test::Script than specified

### ISSUE THREAD

**Issue by jwrightecs** [perl-ide/App-perlvars#1]
t/perlvars.t requires 'script_fails' from Test::Script which was introduced in Test::Script@1.28_01 / 1.29, but the requirements specify Test::Script 1.27 or higher, causing the package to fail to install (at make test)  on systems with Test::Script@1.27

**Comment by oalders** [comment]
Thanks, @jwrightecs! I will release a new version shortly.
