### ISSUE TITLE
Adaptation needed to Test-Vars-0.017

### ISSUE THREAD

**Issue by jkeenan** [perl-ide/App-perlvars#17]
In https://github.com/perl-ide/App-perlvars/issues/4, you worked around certain failures in Test-Vars-0.15.  These workarounds need to be reverted, or at least re-examined, because today I released to CPAN Test-Vars-0.17, which (thanks to a patch by @richardleach) now takes into account two new Perl 5 opcodes released two years ago.  That upgrade to Test-Vars is now triggering test failures for App-perlvars on CPANtesters.  See, *e.g.,* http://www.cpantesters.org/cpan/report/56326b78-7429-11ef-9304-ada65f9eeae7.

**Comment by oalders** [comment]
@hakonhagland do you have any interest in handling this?

**Comment by hakonhagland** [comment]
@oalders See https://github.com/perl-ide/App-perlvars/pull/18

**Comment by oalders** [comment]
Thanks, @jkeenan. New release has just been uploaded to CPAN thanks to 🚀 work by @hakonhagland.
