### ISSUE TITLE
Test fail for perl > 5.37

### ISSUE THREAD

**Issue by yewtc** [perl-ide/App-perlvars#4]
`sub bar {
    my $four = 4; 
}`

This is from the test suite in Unused.pm.   Before 5.37 (I assume as  tests fail from tests from for 5.37 forwards) ` $four` would not be considered as unused. It is now. I was going to "fix" the tests and do a pull request, but I'm not sure that is the correct solution. I think it's possible that this is a bug in perl 5.37+ or at least a change in behaviour.   As `$four` is unused we could be tempted to remove the line, but that will change the behaviour of the function.  The simplest fix for this is to replace `my $four = 4; `with `4;` in the suite, but that feels bad.  Your comment ` this probably should trigger an error`  hints you've thought about the issue before.

**Comment by oalders** [comment]
> but that will change the behaviour of the function

This strikes as me as something that should be flagged by `perlvars`, since it's the kind of code I would generally want to delete as unused.

**Comment by hakonhagland** [comment]
Hi, I was assigned this repository by https://pullrequest.club/, @oalders do you want me to look into this test failure, or some other issues? I guess the test failure will be resolved as soon as the issue https://github.com/houseabsolute/p5-Test-Vars/issues/47 in `Test::Vars` has been resolved. Alternatively, we can make some conditional checks on Perl version in the test files to work around the failures temporarily until the issue in `Test::Vars` has been resolved? Any ideas?

**Comment by oalders** [comment]
Hi @hakonhagland! I don't know if this repo needs anything else, but I guess adding a conditional to get that test to pass or turning the `p5-test-vars` issue into a pull request would probably get us to the same place.

**Comment by oalders** [comment]
Closed via #12
